# Generated by Django 5.1.4 on 2025-02-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('catagory', models.CharField(choices=[('MO', 'Mens Outfit'), ('WO', 'Womens Outfit'), ('KO', 'Kids Outfit')], max_length=100)),
                ('image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
